spring:
  application:
    name: coffee-order-api
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop # DEV_ONLY
  liquibase:
    enabled: true

    drop-first: true # DEV_ONLY
  jackson:
    property-naming-strategy: SNAKE_CASE

# Feature flags
discounts:
  enabled: true
  twenty-five-percent: true
  free-item-after-three: true